### PR TITLE
Inlining of map and set and detection when they are used

### LINKED ISSUE #154: Add Map/Set to lualibfeatureset if used
Possible places to check if map/set is used: 
* `transpileNew`: this might not work if map/set is used in an external library that doesn't do inlining.
* `transpileVaraibleDeclaration` will this cover all cases?
* `transpileNew` + object access: (function call or property access to Maps/Sets) should guarantee that Map/Set is inlined when used somewhere

We should probably also implement it in a way we can easily add other JS internal classes.

### PR DESCRIPTION
**Pull request by Perryvw**
Detect when Map and Set are used and inline them.

Set test lualibimport to "require" by default.

Require now only adds the require statement if any lualib features are detected.

Added an "always" option for luaLibImport to always add the require to the lualib bundle.

Also some general fixes to the lualib imports and inlining.
Closes #154.

Fixes an issue with inlining order as mentioned in #155.

### CODE REVIEW

File: src/Transpiler.ts [hunk 1]
```diff
@@ -1673,4 +1690,17 @@ export abstract class LuaTranspiler {
 
         return result;
     }
+
+    public checkForLuaLibType(type: ts.Type): void {
```
Comment (lolleko) [inline src/Transpiler.ts]: The naming of this function seems a bit of to me. As it checks for the time, but also adds the feature.
