### PR TITLE
Dot slash path fix

### LINKED ISSUE #425: ExportDeclaration require string cut off on Windows
```ts
export { GCOptimizedMap } from "./src/gc_optimized_map";
export { GCOptimizedSet } from "./src/gc_optimized_set";
```

produces

```lua
local exports = exports or {};
do
    local __TSTL_gc_optimized_map = require("rc.gc_optimized_map");
    local GCOptimizedMap = __TSTL_gc_optimized_map.GCOptimizedMap;
    exports.GCOptimizedMap = GCOptimizedMap;
end
do
    local __TSTL_gc_optimized_set = require("rc.gc_optimized_set");
    local GCOptimizedSet = __TSTL_gc_optimized_set.GCOptimizedSet;
    exports.GCOptimizedSet = GCOptimizedSet;
end
return exports;
```

### PR DESCRIPTION
**Pull request by hazzard993**
Fixes #425

I use `path` to parse and format both paths so that there is no leading `/` and the slashes are both the same kind.

Added some tests as well to make sure this stops happening.

### CODE REVIEW

File: src/LuaTransformer.ts [hunk 1]
```diff
@@ -3811,12 +3811,12 @@ export class LuaTransformer {
     }
 
     private getImportPath(relativePath: string): string {
-        const rootDir = this.options.rootDir || path.resolve(".");
-        const absoluteImportPath = this.formatPathToLuaPath(this.getAbsoluteImportPath(relativePath));
-        const absoluteRootDirPath = this.formatPathToLuaPath(rootDir);
+        const rootDir = this.options.rootDir && path.resolve(this.options.rootDir) || path.resolve(".");
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: I'm not entirely sure what I'm looking at but it looks like a lua ternary conditional? In TS those look like: `this.options.rootDir ? path.resolve(this.options.rootDir) : path.resolve(".")`

Comment (hazzard993) [reply src/LuaTransformer.ts]: Been writing too much Lua, I'll turn that into a normal ternary
