### PR TITLE
fixes various issues with translating assignment operators...

### LINKED ISSUE #221: Issues with non-lua operators on properties of objects
Operators such as '+=', '++', etc... can be broken easily right now.

Example 1:
```ts
declare function foo(): number;
declare const a: number[];
a[foo()]++;
```
=>
```lua
a[(foo())+1] = (a[(foo())+1]+1);
```
Here foo() will be called multiple times, producing possibly different values each time or having other undesired side-effects.

Example 2:
```ts
declare function bar(): number[];
let f = bar()[0]++;
```
=>
```lua
local f = (function()
    local __originalValuebar()[(0)+1]0 = bar()[(0)+1];
    bar()[(0)+1] = (bar()[(0)+1]+1);
    return __originalValuebar()[(0)+1]0
end
)();
```
This one won't even compile in lua.

These kinds of issues could be solved by detecting if the value being operated on is a property and caching the object and index parts before performing the operation. This could be wrapped in specialized polyfill functions like the ternary operator is:
```lua
function __TS__PropertyPostInc(o, i)
    local original = o[i]
    o[i] = o[i] + 1
    return original
end

--Example 1
__TS__PropertyPostInc(a, foo())

--Example 2
local f = __TS__PropertyPostInc(bar(), 0)
```

### LINKED ISSUE #225: Problems with assignments as expressions
Similar to #221, evaluating assignments as expression has some issues.

Example:
```ts
declare function a(): number[];
declare function b(): number;
declare function c(): number;
declare const d: number[];
let e = ( a()[b()] = c() );
```
Currently produces:
```lua
local e = ((function() a()[(b())+1] = c(); return a()[(b())+1] end)());
```
The problem here being that a and b are called twice having potentially undesired effects.

A solution could be to cache with a temp:
```lua
local e = ((function() local __temp = c(); a()[(b())+1] = __temp; return __temp end)());
```
But there's a subtle problem with this. Now, c is called before a and b. This would cause issues if c depends on a or b. _shudder_

The only way I can think of to execute it all correctly would be to use another lambda:
```lua
local e = ((function() local __temp; a()[(b())+1] = (function() __temp = c(); return __temp end)(); return __temp end)());
```
At this point things should work correctly but it's very ugly and not great performance-wise.

### PR DESCRIPTION
**Pull request by tomblind**
fixes #221
fixes #225 

There's a lot of cases here but here's the gist:

Simple statements remain largely the same. The exception being statements where the left-side is a "complex" property access:
```ts
arr[getIndex()] += 1;
getObj().prop += 1;
```
```lua
do local __TS_obj, __TS_index = arr, (getIndex())+1; __TS_obj[__TS_index] = (__TS_obj[__TS_index]+(1)); end;
do local __TS_obj, __TS_index = getObj(), "prop"; __TS_obj[__TS_index] = (__TS_obj[__TS_index]+(1)); end;
```
"Complex" meaning the object or property is not a simple literal or variable.

Expressions are similar but will cache the right-side in a temp if it is complex:
```ts
z = x = obj.prop;
z = obj.prop += 1;
```
```lua
z = ((function() local __TS_tmp = obj.prop; x = __TS_tmp; return __TS_tmp end)());
z = (function() local __TS_tmp = obj.prop+1; obj.prop = __TS_tmp; return __TS_tmp end)();
```

And if the left-side is a complex property access everything gets cached (using function args):
```ts
z = getObj().prop += 1;
```
```lua
z = (function(o, i, v) v = (o[i]+v); o[i] = v; return v end)(getObj(), "prop", 1);
```
The plan was to use lib polyfills for these but I have opted to skip that for now. It only affects edge-cases with complex property accesses. Also, bitwise operators would require separate implementations for each lua target.

There are also special implementations for destructuring assignments:
```ts
[x, y] = xTup;
xTup = [x, y] = yTup;
```
```lua
do local __TS_tmp0,__TS_tmp1 = table.unpack(xTup); x,y = __TS_tmp0,__TS_tmp1 end;
xTup = ((function(...) x,y = ...; return {...} end)(table.unpack(yTup)));
```
I discovered that in JS (or node.js at least), desturcturing assignments evaluate the right side first and then the left. I assume this is to make it simple for older ES polyfills to use temp variables. This is why I implemented the statement version with temps - to ensure execution order matches the equivalent JS.

There's an extensive set of tests added (both functional and translation). Feel free to drop questions on me as this is fairly complex and has a lot of what-if scenarios.

### CODE REVIEW

File: src/TSHelper.ts [hunk 1]
```diff
@@ -200,4 +200,31 @@ export class TSHelper {
...
+
+    // Returns true for expressions that may have effects when evaluated
+    public static isExpressionWithEffect(node: ts.Expression): boolean {
+        return !(ts.isLiteralExpression(node) || ts.isIdentifier(node));
+    }
+
+    // If expression is property/element access with possible effects from being evaluated, returns true along with the
+    // separated object and index expressions.
+    public static isAccessExpressionWithEffects(node: ts.Expression, checker: ts.TypeChecker):
+        [true, ts.Expression, ts.Expression] | [false, null, null] {
```
[the remark this answers is not in the document]
Comment (tomblind) [reply src/TSHelper.ts]: I did this out of habit because I usually use strict null checks and this allows TS to deduce the subsequent types in the tuple by evaluating the first. But you're right, without strict null checks they are equivalent and the later is more succinct.

[the remark this answers is not in the document]
Comment (Perryvw) [reply src/TSHelper.ts]: I see. I agree in that case that is actually a nice way of defining the type.

**Comment by tomblind** [comment]
> the implementation of transpileAssignmentExpression looks very low level and I would prefer if it could be generalized a little. I am afraid it is too focussed on the current issues and will not deal well with cases we missed at this current moment.

Did you have something particular in mind? I can break it down into smaller manageable methods and generalize a tiny bit between a couple of the cases, but most of them are fairly distinct and tough to generalize because of subtle differences (which values get cached in temps, etc...).

**Comment by tomblind** [comment]
Alrighty, I've made changes and added tests  based on your feedback. I refactored transpileAssignmentExpression in a way that hopefully makes it a bit more maintainable. It now generates an assignment statement and decides to wrap it as an expression at the end instead of having separate code paths for expressions/statements. This changes the output lua a bit, but makes it more consistent which is probably a good thing. The important thing is that it provides a single place to add new exceptions/rules as situations we haven't thought of yet come up. let me know what you think.

Thanks for taking the time to comb through this!

File: test/unit/math.spec.ts [hunk 2]
```diff
@@ -98,6 +123,35 @@ export class MathTests {
...
     }
 
+    @TestCase("++of().p.d", "o=4;a=6")
+    @TestCase("of().p.d++", "o=4;a=6")
+    @TestCase("--of().p.d", "o=2;a=6")
+    @TestCase("of().p.d--", "o=2;a=6")
+    @TestCase("of().p.d += af()[i()][i()]", "o=9;a=6")
+    @TestCase("of().p.d -= af()[i()][i()]", "o=-3;a=6")
+    @TestCase("of().p.d *= af()[i()][i()]", "o=18;a=6")
+    @TestCase("af()[i()][i()] /= of().p.d", "o=3;a=2.0")
```
Comment (Perryvw) [inline test/unit/math.spec.ts]: This seems to be exactly what I would expect, maybe it would be nice to also check the other elements in a have not changed though, maybe.

File: test/translation/lua/assignments.lua [hunk 3]
```diff
@@ -43,23 +43,23 @@ obj.prop = (obj.prop & arr[(0)+1]);
...
+do local __TS_obj, __TS_index = getArr(), (getIndex())+1; local __TS_tmp = (__TS_obj[__TS_index]%(getObj().prop)); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getArr(), (getIndex())+1; local __TS_tmp = (__TS_obj[__TS_index]^(getObj().prop)); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getObj(), "prop"; local __TS_tmp = (__TS_obj[__TS_index] | (getArr()[(getIndex())+1])); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getObj(), "prop"; local __TS_tmp = (__TS_obj[__TS_index] & (getArr()[(getIndex())+1])); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getObj(), "prop"; local __TS_tmp = (__TS_obj[__TS_index] ~ (getArr()[(getIndex())+1])); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getObj(), "prop"; local __TS_tmp = (__TS_obj[__TS_index] << (getArr()[(getIndex())+1])); __TS_obj[__TS_index] = __TS_tmp; end;
+do local __TS_obj, __TS_index = getObj(), "prop"; local __TS_tmp = (__TS_obj[__TS_index] >> (getArr()[(getIndex())+1])); __TS_obj[__TS_index] = __TS_tmp; end;
 z = ((function() x = y; return y end)());
 z = ((function() obj.prop = x; return x end)());
```
Comment (Perryvw) [inline test/translation/lua/assignments.lua]: Just a general remark regarding translation tests: We don't really value them that much (and are considering maybe just getting rid of them in favor of functional tests). This under the reasoning that we don't really care that much about what our resulting lua looks like, as long as it works. For now I'm fine with these though since this does ensure the stability of our translation.

File: test/unit/math.spec.ts (hunk 2 above)
Comment (tomblind) [reply test/unit/math.spec.ts]: Good point

File: test/translation/lua/assignments.lua (hunk 3 above)
Comment (tomblind) [reply test/translation/lua/assignments.lua]: I agree the translation tests should not be taken as seriously as the functional, but I wouldn't remove them as they force you to pay attention when something changes in the output lua that may have unintended consequences. Perhaps something the functional tests miss, or maybe the result is still correct but the new generated lua is terribly inefficient. But yes, I think they should only be a back-up to the functional tests, not a replacement.
